create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique,display_name text,avatar_url text,bio text,created_at timestamptz default now());
create table if not exists public.items(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,name text not null,description text not null,category text not null check(category in('Cars','Tech','Fashion','Books','Music','Objects','Other')),tags text[] not null default '{}',source_url text,image_url text,created_at timestamptz default now());
create table if not exists public.item_votes(item_id uuid references public.items(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,created_at timestamptz default now(),primary key(item_id,user_id));
create table if not exists public.saved_items(item_id uuid references public.items(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,created_at timestamptz default now(),primary key(item_id,user_id));
create table if not exists public.lists(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,title text not null,description text,created_at timestamptz default now());
create table if not exists public.list_items(list_id uuid references public.lists(id) on delete cascade,item_id uuid references public.items(id) on delete cascade,position int default 0,created_at timestamptz default now(),primary key(list_id,item_id));
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name,avatar_url) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'),new.raw_user_meta_data->>'avatar_url') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.items enable row level security; alter table public.item_votes enable row level security; alter table public.saved_items enable row level security; alter table public.lists enable row level security; alter table public.list_items enable row level security;
create policy "profiles read" on public.profiles for select using(true); create policy "profiles own update" on public.profiles for update using(auth.uid()=id);
create policy "items read" on public.items for select using(true); create policy "items insert" on public.items for insert to authenticated with check(auth.uid()=user_id); create policy "items update" on public.items for update using(auth.uid()=user_id); create policy "items delete" on public.items for delete using(auth.uid()=user_id);
create policy "votes read" on public.item_votes for select using(true); create policy "votes insert" on public.item_votes for insert to authenticated with check(auth.uid()=user_id); create policy "votes delete" on public.item_votes for delete to authenticated using(auth.uid()=user_id);
create policy "saves read" on public.saved_items for select to authenticated using(auth.uid()=user_id); create policy "saves insert" on public.saved_items for insert to authenticated with check(auth.uid()=user_id); create policy "saves delete" on public.saved_items for delete to authenticated using(auth.uid()=user_id);
create policy "lists read" on public.lists for select using(true); create policy "lists insert" on public.lists for insert to authenticated with check(auth.uid()=user_id); create policy "lists update" on public.lists for update using(auth.uid()=user_id); create policy "lists delete" on public.lists for delete using(auth.uid()=user_id);
create policy "list items read" on public.list_items for select using(true); create policy "list items insert" on public.list_items for insert to authenticated with check(exists(select 1 from public.lists l where l.id=list_id and l.user_id=auth.uid())); create policy "list items delete" on public.list_items for delete to authenticated using(exists(select 1 from public.lists l where l.id=list_id and l.user_id=auth.uid()));
create index if not exists items_created_idx on public.items(created_at desc); create index if not exists items_category_idx on public.items(category);
